# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cat',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
