# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spca_app', '0002_auto_20160928_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='adopted',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='adopted',
        ),
    ]
