# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spca_app', '0003_auto_20160928_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='num_pic',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='num_pic',
        ),
        migrations.AddField(
            model_name='cat_pic',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dog_pic',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
