# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spca_app', '0004_auto_20160928_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='need_compation',
            new_name='need_companion',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='comment_top',
        ),
        migrations.AddField(
            model_name='dog',
            name='special_need',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
